spring.application.name=vencimientos

# CONFIGURACIÓN PARA BASE DE DATOS POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/minimarket_db
spring.datasource.username=postgres
spring.datasource.password=granados123

# Mantiene los datos reales guardados para siempre y solo actualiza los cambios
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Muestra las consultas en la consola de IntelliJ
spring.jpa.show-sql=true